name: Deploy to S3 on Push

on:
  push:
    branches: [main]
    
jobs:
  Integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12.0
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test code
      run: |
        python CounterFunction/test_main.py
    
  Deployment:
    needs: Integration
    runs-on: ubuntu-latest
    steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{secrets.AWS_REGION_NAME}}
    - name: print working dir
      run: pwd
    - name: list directory
      run: ls
    - name: zip code
      run: zip -r CounterFunction.zip ./Backend/CounterFunction
    - name: Deploy to Lambda
      run: aws lambda update-function-code \
             --function-name CounterStack-CounterFunction-pkgcrkfU4115 \
             --zip-file fileb://CounterFunction.zip
      #run: aws s3 sync . s3://staticbucket3782
    

        
    
    
      
